### ISSUE TITLE
Not all tests in the regression suite pass

### ISSUE THREAD

**Issue by NathanDunfield** [bzhan/bfh_python#3]
In testing pull request #2, I got the following 2 failures, which I believe are unrelated to #2.
```
% python3 regression.py
[...]
======================================================================
ERROR: testMultiply (minusalgtest.MinusAlgTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bfh_python/minusalgtest.py", line 17, in testMultiply
    self.assertEqual(len(gen.factor()), 1 + sum(gen.multiplicity))
  File "bfh_python/algebra.py", line 70, in factor
    return self.parent.factor(self)
  File "bfh_python/algebra.py", line 557, in factor
    return self._getFactorMap()[gen]
KeyError: [0->0]

======================================================================
ERROR: testSignedMultiply (signstest.PreStrandAlgebraTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bfh_python/signstest.py", line 108, in testSignedMultiply
    algebra.grSign(gen1) * gen1 * gen2.diff())
AttributeError: 'PreStrandAlgebra' object has no attribute 'grSign'

----------------------------------------------------------------------
Ran 200 tests in 4181.145s
```

**Comment by NathanDunfield** [comment]
Closed by 69e8f88.
